spring.application.name=kafka-order-producer

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.topic.order=order-service
spring.kafka.topic.order.dlt=order-service.DLT
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Logging
logging.level.org.apache.kafka.common.config.AbstractConfig=WARN
